#!/usr/bin/env python3
import os, sys

_srcdir = '%s/src/' % os.path.dirname(os.path.realpath(__file__))
_filepath = os.path.dirname(sys.argv[0])
sys.path.insert(1, os.path.join(_filepath, _srcdir))

if sys.version_info[0] == 3:
    import novel_get
    if __name__ == '__main__':
        novel_get.main(url=sys.argv[1])
else:
    print("[FATAL] Python 3 is required!")
